import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import customFont from "next/font/local";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ContextProvider from "@/hooks/useContext/ContextProvider";

export const metadata: Metadata = {
  title: "HealthCare Diet",
  description: "Generated by create next app",
};

const yekanBakh = customFont({
  src: [{path:'./../../public/fonts/YekanBakh-Regular.ttf'}]
})

const inter = Inter({
  subsets: ["latin-ext"],
  weight: ["400", "500", "600", "700", "800"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ContextProvider>
        <body className={yekanBakh.className}>
          {children}
          <ToastContainer
            // transition={'zoom'}
            autoClose={2500}
            rtl={true}
            position="bottom-right"
          />
        </body>
      </ContextProvider>
    </html>
  );
}
